### ISSUE TITLE
Update can_edit permission documentation to include uploading changes to the server

### ISSUE THREAD

**Issue by kitsao** [medic/cht-docs#721] opened 2022-06-30 11:11 UTC
The permission doesn't stop you from editing documents, but only uploading those edits to CouchDB. References [config-pih #621](https://github.com/medic/config-pih/issues/621)

**Comment by garethbowen** [comment] 2022-06-30 18:19
I think this is a duplicate of https://github.com/medic/cht-docs/issues/718

**Closed by garethbowen** 2022-06-30 18:19 UTC
Labels: retro-action-item
