### ISSUE TITLE
Hosting section high level migration

### ISSUE THREAD

**Issue by esthermmoturi** [medic/cht-docs#1359] opened 2024-04-22 13:02 UTC
This is to ensure all available documentation in regards to hosting has been grouped and placed as a top-level navigation section.

1.  [Bash script](https://github.com/medic/cht-docs/issues/1351) for checking broken links

**Comment by mrjones-plip** [comment] 2024-04-26 21:26
closing as a dupe of #1351, please re-open if you still need this!

**Closed** 2024-04-26 21:27 UTC
