### ISSUE TITLE
Add documentation related to geolocation

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-docs#296] opened 2020-09-01 15:59 UTC
There is basically no documentation related to `geolocation` in the doc site. Searching for `geolocation` comes up with one thing in [CSV-to-Docs](https://docs.communityhealthtoolkit.org/apps/guides/data/csv-to-docs/) but nothing else. Searching for `gps` comes up with nothing.

At a minimum, I think we should add the JSON snippet mentioned in https://github.com/medic/cht-core/issues/5917#issuecomment-669699496 somewhere in [db-schema](https://docs.communityhealthtoolkit.org/core/overview/db-schema/).  It's an important enough topic that we might also want to add some content to the [Concepts](https://docs.communityhealthtoolkit.org/apps/concepts/) or [Features](https://docs.communityhealthtoolkit.org/apps/features/) section

**Note to author**: The app will wait up to 30 seconds to get a location lock before it gives up. If a user tries to submit a form _before_ a location lock is obtained and _before_ 30 seconds are up, the submit action will _wait_ until 30 seconds are up.  Also: This change also supports the latest updates in medic-android, where the Location permission is requested at runtime, when editing/creating a report, rather than demanded when starting the app for the first time.

**Comment by michaelkohn** [comment] 2020-09-01 16:48
**Note to author**: The app will wait up to 30 seconds to get a location lock before it gives up. If a user tries to submit a form _before_ a location lock is obtained and _before_ 30 seconds are up, the submit action will _wait_ until 30 seconds are up.

**Comment by MaxDiz** [comment] 2020-09-29 13:54
closing as duplicate of https://github.com/medic/cht-docs/issues/326 since the issue contains more detailed info

**Closed by MaxDiz** 2020-09-29 13:54 UTC
Labels: documentation

**Comment by michaelkohn** [comment] 2020-09-29 18:28
@MaxDiz #326 doesn't really address the functional side of things (30 seconds stuff). Please either add it to 326 or reopen this one.
