### ISSUE TITLE
The See Also link on the guides/performance/replication page is not rendering properly

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-docs#285] opened 2020-08-19 15:44 UTC
https://docs.communityhealthtoolkit.org/apps/guides/performance/replication/#code-sample

![Screen Shot 2020-08-19 at 11 40 57 AM](https://user-images.githubusercontent.com/10096985/90658065-1dc51c80-e211-11ea-9cbc-ea47dcf7ed84.png)

**Comment by mrjones-plip** [comment] 2020-08-19 19:19
Thanks for filing @michaelkohn ! 

This is actually working as designed such that when we updated the `see-also`, we explicitly made it so it only worked with `{{< see-also` and not `{{% see-also`.  Docs on how to use this [were updated](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#cross-referencing-content) accordingly. I checked with a recursive `grep` and this is the only instance of  `{{% see-also`, so we should be good!

**Comment by mrjones-plip** [comment] 2020-08-19 19:22
Maybe when @abbyad gets back from holiday we can see about breaking the build when these don't compile?  That would move the pressure on docs AT/PR/code review and into automation that will simply not allow you to push if you have a broken `see-also` or `read-more`.

**Comment by mrjones-plip** [comment] 2020-08-19 20:54
Doing a little look back in history, it looks like the `6352-report-replication-depth` branch for PR #58 was cut before the new `see-also` code existed so the `{{% see-also` was fully valid.  We then cut a branch for #204, developed it and merged it to master on Jul 7th. Then on Jul 13th, the #58  branch got merged, with on conflicts, but explains why doing local testing on that branch didn't show the `see-also` in question rendering wrong.  

We could maybe add a step in code [worklflow docs](https://docs.communityhealthtoolkit.org/contribute/docs/workflow/) to merge from master to your branch and re-test before merging branch to master?  I suppose there's trade offs for doing this though.

**Comment by michaelkohn** [comment] 2020-08-20 18:27
Cool thanks. Understood that there were some PR cutting timelines that may have played into this, so that's no big deal. I mostly just raised the ticket so someone could come back and fix it since I was in the middle of something else. The way it handles the error is fine, though I'd probably prefer it gave me one of the build error messages when i run locally, it's a lot more obvious :-).  


<img width="1062" alt="Screen Shot 2020-08-20 at 2 15 40 PM" src="https://user-images.githubusercontent.com/10096985/90810566-2e4cc400-e2f1-11ea-9ede-e319ac40f4f3.png">

**Closed** 2020-08-26 17:42 UTC
Labels: documentation
